#!/bin/env python3
import os
import leglight
import click

# Uncomment the lines below if you want to use the discovery method instead of fixed IP Address.
# allLights = leglight.discover(2)
# lght = allLights[0]

# The Ring IP address
lightIP = os.getenv("ELGATO_RING_LIGHT_IP")
light   = leglight.LegLight(lightIP,9123)

__author__ = "kinncj"

@click.group()
def main():
    """
    Elgato Ring Commandline
    """
    pass


@main.command()
def toggle():
    if light.isOn == 0:
        light.on()
    else:
        light.off()

@main.command()
@click.argument('temp')
def temperature(temp):
    light.color(int(temp))

@main.command()
@click.argument('bright')
def brightness(bright):
    light.brightness(int(bright))

if __name__ == "__main__":
    main()
