#!/bin/env python3
import os
import leglight
import click

# The Ring IP address
lightIP = os.getenv("ELGATO_RING_LIGHT_IP")

if lightIP:
    light = leglight.LegLight(lightIP,9123)
else:
    allLights = leglight.discover(2)
    light = allLights[0]

__author__ = "kinncj"

@click.group()
def main():
    """
    Elgato Ring Commandline
    """
    pass


@main.command()
def toggle():
    if light.isOn == 0:
        light.on()
    else:
        light.off()

@main.command()
@click.argument('temp')
def temperature(temp):
    light.color(int(temp))

@main.command()
@click.argument('bright')
def brightness(bright):
    light.brightness(int(bright))

if __name__ == "__main__":
    main()
